### DIVE INTO DEEP LEARNING

##### 张量基本操作与属性

In [1]:
import torch

In [2]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x.shape#形状

torch.Size([12])

In [6]:
x.numel()#元素总数

12

In [ ]:
X=x.reshape(2,6)#元素不变,可以用-1自动调整
X

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [9]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
torch.randn(3,4)#服从标准正态分布的随机

tensor([[ 1.0116, -0.9999,  0.7576,  0.4940],
        [-1.0020,  1.5060, -1.3934, -0.0969],
        [-1.5238, -0.7250,  0.8566,  0.9245]])

In [13]:
torch.tensor([[2,1,3,4],[1,2,4,3],[4,3,1,2]])

tensor([[2, 1, 3, 4],
        [1, 2, 4, 3],
        [4, 3, 1, 2]])

##### 运算符

In [14]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y#**为求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [15]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [30]:
X=torch.arange(12,dtype=torch.float32).reshape((3,-1))
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [18]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [19]:
X.sum()

tensor(66.)

##### 广播机制

In [20]:
a=torch.arange(3).reshape((3,-1))
b=torch.arange(2).reshape((-1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [21]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

##### 索引和切片

In [22]:
X[-1],X[1:3]#-1是最后的元素

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [23]:
X[1,2]=9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [31]:
X[0:2,:]=11
X

tensor([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [ 8.,  9., 10., 11.]])

##### 节省内存

In [ ]:
before=id(Y)#获取Y所在地址
Y=Y+X
id(Y)==before
#很多时候我们应该原地进行更新

False

In [35]:
Z=torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:]=X+Y
print('-----------------------')
print('id(Z)',id(Z))

id(Z): 2721432658448
-----------------------
id(Z) 2721432658448


In [36]:
before=id(X)
X+=Y
id(X)==before

True

##### 转换为其他Python对象

In [37]:
A=X.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [40]:
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

##### experiment

In [56]:
S=torch.arange(6).reshape(-1,1)
M=torch.arange(6).reshape(1,-1)
S,M

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5]]),
 tensor([[0, 1, 2, 3, 4, 5]]))

In [57]:
S+M

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5,  6],
        [ 2,  3,  4,  5,  6,  7],
        [ 3,  4,  5,  6,  7,  8],
        [ 4,  5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9, 10]])